export const GET_STATUS_REQUEST = 'GET_STATUS_REQUEST'
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS'
export const GET_STATUS_FAILURE = 'GET_STATUS_FAILURE'
 
export const SEARCH_STATUS_REQUEST = 'SEARCH_STATUS_REQUEST'
export const SEARCH_STATUS_SUCCESS = 'SEARCH_STATUS_SUCCESS'
export const SEARCH_STATUS_FAILURE = 'SEARCH_STATUS_FAILURE'
 
export const ADD_STATUS_REQUEST = 'ADD_STATUS_REQUEST'
export const ADD_STATUS_SUCCESS = 'ADD_STATUS_SUCCESS'
export const ADD_STATUS_FAILURE = 'ADD_STATUS_FAILURE'
 
export const UPDATE_STATUS_REQUEST = 'UPDATE_STATUS_REQUEST'
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS'
export const UPDATE_STATUS_FAILURE = 'UPDATE_STATUS_FAILURE'
 
export const DELETE_STATUS_REQUEST = 'DELETE_STATUS_REQUEST'
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS'
export const DELETE_STATUS_FAILURE = 'DELETE_STATUS_FAILURE'





export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'
 
export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST'
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS'
export const SEARCH_USER_FAILURE = 'SEARCH_USER_FAILURE'
 
export const ADD_USER_REQUEST = 'ADD_USER_REQUEST'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE'
 
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'
 
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'